<div class="alert">
<div style="direction:ltr;text-align:center;font-family: B Tahoma; font-size:24pt"> Practical Deep Learning Course for Computer Vision
</div>
</div>

<div class="alert">
<div style="direction:ltr;text-align:left;font-family:Tahoma; font-size:16pt"> Introduction to Computer Vision
</div>
</div>

<div style="direction:ltr;text-align:left;font-family: Tahoma">
In order to install required libraries, execute cell below.
</div>

In [ ]:
!pip install numpy
!pip install opencv-python

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Import the required libraries.<br>
To work with images, we need to import <strong>OpenCV</strong>
</div>

In [1]:
# Import numpy
import numpy as np

# Import OpenCv
import cv2

In [2]:
print(cv2.__version__)

3.4.3


<div style="direction:ltr;text-align:left;font-family: Tahoma">
<strong>I/O operations:</strong>
</div>

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Loading an image:
</div>

In [3]:
# Load the image
image = cv2.imread('./images/flower.jpg')

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Displaying the loaded image:
</div>

In [4]:
# Display the image
cv2.imshow('Flower', image)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Writing the image on the disk:
</div>

In [5]:
# Write the image
cv2.imwrite('flower-copy.jpg', image)

True

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Using the webcam:
</div>

In [6]:
# Note: if "0" is passed to "VideoCapture" the source will be the webcam
#       and if the address of a video file is passed to "VideoCapture" the source will be that video
cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    cv2.imshow('Webcam', frame)
    if cv2.waitKey(1) == 13: #13 is the Enter Key
        break
        
# Release camera and close windows
cap.release()
cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
<strong>Simple operations on the image:</strong>
</div>

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Image as a matrix:
</div>

In [7]:
image.shape

(368, 552, 3)

In [8]:
# Print dimensions of the image
print ('Height of the Image:', image.shape[0], 'pixels')
print ('Width of the Image: ', image.shape[1], 'pixels')
print ('Channel(s) of the Image: ', image.shape[2], 'channel(s)')

Height of the Image: 368 pixels
Width of the Image:  552 pixels
Channel(s) of the Image:  3 channel(s)


<div style="direction:ltr;text-align:left;font-family: Tahoma">
Converting the colored image to greyscale:<br>
<strong>Grayscaling</strong> is the process by which an image is converted from a full color to shades of gray.

</div>

In [9]:
# To convert to grayscale, use "cvtColor"
gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

cv2.imshow('Grayscale Flower', gray_image)
cv2.waitKey()

cv2.destroyAllWindows()

In [10]:
gray_image.shape

(368, 552)

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Individual channels in the RGB image:
</div>

In [11]:
# "split" function splits the image into each dimension
B, G, R = cv2.split(image)

# Create a matrix of zeros with dimensions of height and width
zeros = np.zeros(image.shape[:2], dtype = "uint8")

# Note: In OpenCV, the images are in the form of BGR (NOT RGB)
cv2.imshow("Red Channel", cv2.merge([zeros, zeros, R]))
cv2.waitKey()
cv2.imshow("Green Channel", cv2.merge([zeros, G, zeros]))
cv2.waitKey()
cv2.imshow("Blue Channel", cv2.merge([B, zeros, zeros]))
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Pixel values in the image:<br>
As you can see the range for each pixel value is between 0 to 255.
</div>

In [12]:
image[200, 300]

array([201, 157, 194], dtype=uint8)

In [13]:
image[200, 300] + 20

array([221, 177, 214], dtype=uint8)

In [14]:
image[200, 300] * 2

array([146,  58, 132], dtype=uint8)

<div style="direction:ltr;text-align:left;font-family: Tahoma">
<strong>Draw shapes or put text on the image:</strong>
</div>

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Line:
</div>

In [15]:
image = cv2.imread('./images/flower.jpg')

# Draw a line
cv2.line(image, (0,0), (400,400), (0,255,0), 5)

cv2.imshow("Line", image)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Rectangle:
</div>

In [16]:
image = cv2.imread('./images/flower.jpg')

# Draw a Rectangle
cv2.rectangle(image, (50,100), (300,250), (255,0,0), 5)

cv2.imshow("Rectangle", image)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Circle:
</div>

In [17]:
image = cv2.imread('./images/flower.jpg')

# Draw a Cicle
cv2.circle(image, (200, 200), 100, (50,0,255), 5)

cv2.imshow("Circle", image)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Text:
</div>

In [18]:
image = cv2.imread('./images/flower.jpg')

# Put a text
cv2.putText(image, 'This is a flower!', (10,50), cv2.FONT_HERSHEY_COMPLEX, 1, (200,170,100), 2)

cv2.imshow("Text", image)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
<strong>Image Transformations:</strong>
</div>

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Translation:
</div>

In [19]:
image = cv2.imread('./images/flower.jpg')

cv2.imshow('Original', image) 
cv2.waitKey()

# Store height and width of the image
height, width = image.shape[:2]

quarter_height, quarter_width = height/4, width/4
  
#  T  = | 1 0 Tx |
#       | 0 1 Ty |

# T is our translation matrix
T = np.float32([[1, 0, quarter_width], [0, 1,quarter_height]])

# Use warpAffine to transform the image using the matrix T
img_translation = cv2.warpAffine(image, T, (width, height))

cv2.imshow('Translation', img_translation)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Rotation:
</div>

In [20]:
image = cv2.imread('./images/flower.jpg')

cv2.imshow('Original', image) 
cv2.waitKey()

# Store height and width of the image
height, width = image.shape[:2]

half_height, half_width = height/2, width/2

# T is the rotation matrix
T = cv2.getRotationMatrix2D((half_width, half_height), 20, 1)

# Use warpAffine to rotate the image using the matrix T around its centre
rotated_image = cv2.warpAffine(image, T, (width, height))

cv2.imshow('Rotation', rotated_image)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Transpose:
</div>

In [21]:
image = cv2.imread('./images/flower.jpg')

cv2.imshow('Original', image) 
cv2.waitKey()

# Use "transpose" method to flip a the image over its diagonal (switches the row and column indices of the matrix)
rotated_image = cv2.transpose(image)

cv2.imshow('Rotation - Method 2', rotated_image)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Flip:
</div>

In [22]:
image = cv2.imread('./images/flower.jpg')

cv2.imshow('Original', image) 
cv2.waitKey()

# Horizontal flip
flipped = cv2.flip(image, 1)

cv2.imshow('Horizontal Flip', flipped) 
cv2.waitKey()

# Vertical flip
flipped = cv2.flip(image, 0)

cv2.imshow('Vertical Flip', flipped) 
cv2.waitKey()

# Horizontal and Vertical flip
flipped = cv2.flip(image, -1)

cv2.imshow('Horizontal and Vertical Flip', flipped) 
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Resize:
</div>

In [23]:
image = cv2.imread('./images/flower.jpg')

cv2.imshow('Original', image) 
cv2.waitKey()

# Make the image half of it's original size
image_scaled = cv2.resize(image, None, fx=0.5, fy=0.5)
cv2.imshow('Scaling - Linear Interpolation', image_scaled)
cv2.waitKey()

# Make the image double the size of it's original size
# Note: You can use different "interpolation(s)"
img_scaled = cv2.resize(image, None, fx=2, fy=2, interpolation = cv2.INTER_CUBIC)
cv2.imshow('Scaling - Cubic Interpolation', img_scaled)
cv2.waitKey()

# Resizing by setting exact dimensions
img_scaled = cv2.resize(image, (300, 400), interpolation = cv2.INTER_AREA)
cv2.imshow('Scaling - Size of (300, 400)', img_scaled) 
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Crop:
</div>

In [24]:
image = cv2.imread('./images/flower.jpg')

cv2.imshow("Original", image)
cv2.waitKey()

# Crop out the arbitray area
cropped = image[100:300 , 200:800, :]

cv2.imshow("Cropped", cropped)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
<strong>Advanced operations on the image:</strong>
</div>

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Convolution:
</div>

<img src="./images/Convolution_schematic.gif" alt="Convolution Schematic">
<a href="https://i.pinimg.com/originals/19/c2/3b/19c23b1be24b010884a0238def115b86.gif">Reference</a>

In [25]:
# Note: By passing "0" to "imread" method, the image will be read in grayscale format
image = cv2.imread('./images/flower.jpg', 0)

cv2.imshow('Original', image)
cv2.waitKey()

# Resize the image to reduce the computation for convolution!
img_scaled = cv2.resize(image, (300, 300), interpolation = cv2.INTER_AREA)

cv2.imshow('Resized', img_scaled)
cv2.waitKey()

# Creating a 3 x 3 kernel
# Note:  Moving Average Filter 
kernel_3x3 = np.ones((3, 3), np.float32) / 9

# Use the "fitler2D" method to conovlve the kernal on the image 
blurred_3x3 = cv2.filter2D(img_scaled, -1, kernel_3x3)
cv2.imshow('3x3 Kernel Blurring', blurred_3x3)
cv2.waitKey()

# Creating a 7 x 7 kernel
kernel_7x7 = np.ones((7, 7), np.float32) / 49

blurred_7x7 = cv2.filter2D(img_scaled, -1, kernel_7x7)
cv2.imshow('7x7 Kernel Blurring', blurred_7x7)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Sharpening:
</div>

In [26]:
image = cv2.imread('./images/flower.jpg')

cv2.imshow('Original', image)
cv2.waitKey() 

# Create our shapening kernel
kernel_sharpening = np.array([[-1,-1,-1], 
                              [-1,9,-1], 
                              [-1,-1,-1]])

# applying the kernel to the input image
sharpened = cv2.filter2D(image, -1, kernel_sharpening)

cv2.imshow('Sharpening', sharpened)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Binary Thereshold:
</div>

In [27]:
image = cv2.imread('./images/flower.jpg', 0)

cv2.imshow('Original', image)
cv2.waitKey() 

# Values below 127 goes to 0 (black) and everything above 127 goes to 255 (white)
ret, thresh = cv2.threshold(image, 127, 255, cv2.THRESH_BINARY)

cv2.imshow('Binary Threshold', thresh)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Erosion, Dilation, Opening and Closing:
</div>

<img src="./images/morphology.gif" alt="Convolution Schematic">
<a href="https://www.dspguide.com/graphics/F_25_10.gif">Reference</a>

In [28]:
image = cv2.imread('./images/flower.jpg', 0)

cv2.imshow('Original', image)
cv2.waitKey() 

# The kernel
kernel = np.ones((5,5), np.uint8)

# erosion
erosion = cv2.erode(image, kernel, iterations = 1)
cv2.imshow('Erosion', erosion)
cv2.waitKey()

# dilation
dilation = cv2.dilate(image, kernel, iterations = 1)
cv2.imshow('Dilation', dilation)
cv2.waitKey()

# Opening - Good for removing noise
opening = cv2.morphologyEx(image, cv2.MORPH_OPEN, kernel)
cv2.imshow('Opening', opening)
cv2.waitKey()

# Closing - Good for removing noise
closing = cv2.morphologyEx(image, cv2.MORPH_CLOSE, kernel)
cv2.imshow('Closing', closing)
cv2.waitKey()

cv2.destroyAllWindows()

<div style="direction:ltr;text-align:left;font-family: Tahoma">
Canny Filter:
</div>

<img src="./images/canny2.png" alt="Canny  Filter for Edge Detection">
<a href="https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQ-Rsl7ZWVFh126U9AZ2WiaqE2I6wisV-vb9wJy_GS5k92sobyc">Reference</a>

In [29]:
image = cv2.imread('./images/flower.jpg', 0)

cv2.imshow('Original', image)
cv2.waitKey()

# Canny  Filter for Edge Detection
canny = cv2.Canny(image, 60, 120)

cv2.imshow('Canny', canny)
cv2.waitKey()

cv2.destroyAllWindows()

<div class="alert">
<div style="direction:ltr;text-align:left;font-family:B Tahoma"> Practical Deep Learning Course for Computer Vision
<br>Vahid Reza Khazaie<br>
</div>
<a href="https://www.linkedin.com/in/vahidrezakhazaie/">LinkedIn</a> - <a href="https://github.com/vrkh1996">GitHub</a>

</div>